version: '3.7'

services:
    worker:
        build:
            context: ./worker
        image: worker
        restart: unless-stopped
        # depends_on:
        #   - db
        expose:
            - "5000"
        # deploy:
        #     replicas: 3

    stateful:
        build:
            context: ./stateful
        image: stateful
        container_name: stateful
        restart: unless-stopped
        # depends_on:
        #   - db
        expose:
            - "5001"

    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - worker
            - db
            - stateful
        ports:
            - "127.0.0.1:4000:80"

    db:
        image: mysql:5.7
        container_name: db
        hostname: db
        ports:
            - "3306:3306"
            # - "127.0.0.1:3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: worker
            MYSQL_PASSWORD: '123456'
            MYSQL_DATABASE: games